project_id = "clqbumovauiuoeizwbhd"

[functions.create-checkout-session]
verify_jwt = false

[functions.save-order]
verify_jwt = false

[functions.fetch-orders]
verify_jwt = false

[functions.fetch-subscriptions]
verify_jwt = false

[functions.fetch-dashboard-stats]
verify_jwt = false

[functions.notify-appointment-telegram]
verify_jwt = false

[functions.dispatch-appointment-reminders]
verify_jwt = false

[functions.fetch-reservations]
verify_jwt = false

[functions.update-reservation-status]
verify_jwt = false

[functions.manage-notification]
verify_jwt = false
